# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZFRE9bKIqmiodTT_ce0Yt4_9cCJHCps
"""



import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
import random

def narysuj_swiateczna_scene():
    """
    Rysuje pełną świąteczną scenę z Mikołajem, choinką i śnieżnym tłem
    przy użyciu Matplotlib i zwraca obiekt figury.
    """

    # 1. Ustawienia sceny i tła
    # Zwracamy fig i ax, aby Streamlit mógł je poprawnie wyświetlić
    fig, ax = plt.subplots(figsize=(10, 8))

    # Paleta kolorów sceny
    niebo_kolor = '#0B1026'  # Bardzo ciemny granat
    snieg_kolor = '#F0F8FF'  # AliceBlue (złamana biel)
    c_red = '#D62828'      # Czerwony Mikołaj
    c_skin = '#FFDFC4'     # Skóra

    ax.set_facecolor(niebo_kolor)
    ax.set_xlim(0, 20)
    ax.set_ylim(0, 16)
    ax.set_aspect('equal')
    ax.axis('off')

    # --- TŁO: ŚNIEG I ZIEMIA ---
    # Zaspa śnieżna na dole
    zaspa = patches.Ellipse((10, 0), 25, 6, facecolor=snieg_kolor, zorder=0)
    ax.add_patch(zaspa)

    # Padający śnieg (losowe kropki na niebie)
    np.random.seed(42)
    x_snow = np.random.uniform(0, 20, 100)
    y_snow = np.random.uniform(3, 16, 100)
    sizes = np.random.uniform(10, 60, 100)
    ax.scatter(x_snow, y_snow, s=sizes, color='white', alpha=0.6, edgecolors='none', zorder=1)

    # --- FUNKCJE POMOCNICZE ---
    def add_circle(x, y, r, color, z=1, ec='black', lw=0.5):
        ax.add_patch(patches.Circle((x, y), r, facecolor=color, edgecolor=ec, linewidth=lw, zorder=z))

    def add_ellipse(x, y, w, h, angle, color, z=1, ec='black'):
        ax.add_patch(patches.Ellipse((x, y), w, h, angle=angle, facecolor=color, edgecolor=ec, linewidth=0.5, zorder=z))

    # --- CHOINKA (Po prawej stronie) ---
    tree_x = 15
    tree_y_base = 3

    # Pień
    ax.add_patch(patches.Rectangle((tree_x - 0.5, tree_y_base), 1, 2, facecolor='#5D4037', zorder=2))

    # Warstwy choinki (zielone trójkąty)
    green_shades = ['#1B4332', '#2D6A4F', '#40916C']
    widths = [5, 4, 3]
    heights = [3, 2.5, 2]
    y_levels = [4, 5.5, 7]

    for i in range(3):
        w = widths[i]
        h = heights[i]
        y = y_levels[i]
        path = [
            (tree_x - w/2, y),
            (tree_x + w/2, y),
            (tree_x, y + h)
        ]
        poly = patches.Polygon(path, closed=True, facecolor=green_shades[i], edgecolor='#081c15', zorder=3+i)
        ax.add_patch(poly)

    # Bombki na choince
    bombki_pos = [
        (14, 4.5), (16, 4.8), (15, 5.2),
        (14.5, 6), (15.5, 6.2),
        (15, 7.5)
    ]
    colors = ['red', 'gold', 'red', 'blue', 'gold', 'red']
    for idx, pos in enumerate(bombki_pos):
        add_circle(pos[0], pos[1], 0.25, colors[idx], z=10, ec='none')

    # Gwiazda na czubku
    ax.scatter(tree_x, 9.2, s=400, marker='*', color='gold', zorder=10, edgecolors='orange')


    # --- ŚWIĘTY MIKOŁAJ (Po lewej stronie) ---
    sx = 6
    sy = 3

    # Buty
    add_ellipse(sx-1.5, sy, 1.8, 1.2, 0, 'black', z=2)
    add_ellipse(sx+1.5, sy, 1.8, 1.2, 0, 'black', z=2)

    # Nogi
    ax.add_patch(patches.Rectangle((sx-2, sy), 1.5, 3, facecolor=c_red, zorder=1))
    ax.add_patch(patches.Rectangle((sx+0.5, sy), 1.5, 3, facecolor=c_red, zorder=1))

    # Brzuch
    add_ellipse(sx, sy+4, 6, 5.5, 0, c_red, z=3)

    # Pas
    add_ellipse(sx, sy+3.5, 6.1, 1, 0, 'black', z=4, ec='none')
    ax.add_patch(patches.Rectangle((sx-0.8, sy+3.1), 1.6, 0.8, facecolor='gold', zorder=5))

    # Ręce
    add_ellipse(sx-2.8, sy+4.5, 3, 1.2, -30, c_red, z=2)
    add_ellipse(sx+2.8, sy+4.5, 3, 1.2, 30, c_red, z=2)

    # Rękawice
    add_circle(sx-3.8, sy+3.8, 0.7, '#1D3557', z=3)
    add_circle(sx+3.8, sy+3.8, 0.7, '#1D3557', z=3)

    # Głowa
    head_y = sy+7.2
    add_circle(sx, head_y, 1.6, c_skin, z=4)

    # --- ULEPSZONA BRODA ---
    beard_z = 5
    add_ellipse(sx, head_y-1.0, 3.2, 2.5, 0, 'white', z=beard_z, ec='none')

    random.seed(10)
    for _ in range(25):
        bx = sx + random.uniform(-1.4, 1.4)
        by = head_y - 1.0 + random.uniform(-1.5, 0.5)
        r = random.uniform(0.3, 0.5)
        add_circle(bx, by, r, 'white', z=beard_z, ec='lightgray', lw=0.1)

    # Wąsy
    add_ellipse(sx-0.7, head_y-0.4, 1.4, 0.6, -20, 'white', z=beard_z+1)
    add_ellipse(sx+0.7, head_y-0.4, 1.4, 0.6, 20, 'white', z=beard_z+1)

    # Twarz - detale
    add_circle(sx-0.5, head_y+0.2, 0.15, 'black', z=6)
    add_circle(sx+0.5, head_y+0.2, 0.15, 'black', z=6)
    add_circle(sx, head_y-0.2, 0.25, '#E07A5F', z=6)
    add_circle(sx-0.9, head_y-0.1, 0.25, '#FFC0CB', z=5, ec='none')
    add_circle(sx+0.9, head_y-0.1, 0.25, '#FFC0CB', z=5, ec='none')

    # Czapka
    add_ellipse(sx, head_y+1.2, 3.4, 0.8, 0, 'white', z=7)
    czapka_poly = patches.Polygon([(sx-1.6, head_y+1.2), (sx+1.6, head_y+1.2), (sx+2.5, head_y+3.5)],
                                  facecolor=c_red, zorder=6)
    ax.add_patch(czapka_poly)
    add_circle(sx+2.5, head_y+3.5, 0.5, 'white', z=8)

    # --- PREZENT ---
    px, py = 10, 2
    ax.add_patch(patches.Rectangle((px, py), 2.5, 2.5, facecolor='#4361EE', ec='black', zorder=2))
    ax.add_patch(patches.Rectangle((px+1, py), 0.5, 2.5, facecolor='gold', zorder=3))
    ax.add_patch(patches.Rectangle((px, py+1), 2.5, 0.5, facecolor='gold', zorder=3))

    ax.set_title("Wesołych Świąt!", color='white', fontsize=18, fontweight='bold')

    # Zwracamy całą figurę
    return fig

# --- Główna funkcja Streamlit ---
def main():
    st.set_page_config(page_title="Świąteczna Scena Matplotlib", layout="centered")
    st.title("🎄 Interaktywna Scena Świąteczna (Matplotlib + Streamlit)")
    st.markdown("Ten obrazek został wygenerowany w całości za pomocą biblioteki Matplotlib i wyświetlony przez Streamlit.")

    # Wywołanie funkcji rysującej i przekazanie figury do Streamlit
    fig = narysuj_swiateczna_scene()
    st.pyplot(fig)

    st.caption("Użyto bibliotek: Matplotlib, NumPy, Random, Streamlit.")

if __name__ == "__main__":
    main()